targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - movies.schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: movies.schema.graphql
              queries_glob: graphql/popular_movies.graphql
              output: lib/graphql/popular_movies.dart
          scalar_mapping:
            - graphql_type: URL
              dart_type: String
